# Generated by Django 5.2.4 on 2025-07-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OktaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('okta_id', models.CharField(max_length=255, unique=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
